from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

from io import BytesIO
from datetime import datetime
import random


def generate_pdf_report(patient_data, report):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    content = []

    timestamp = datetime.now().strftime(
        "%d-%m-%Y %H:%M"
    )

    report_id = f"KH-{random.randint(100000,999999)}"

    # ==================================================
    # TITLE
    # ==================================================

    title_style = styles["Title"]
    title_style.textColor = colors.darkblue

    content.append(
        Paragraph(
            "AI Kidney Health Assessment Report",
            title_style
        )
    )

    content.append(
        Paragraph(
            "Generated by AI Kidney Health Assessment System",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Report ID: {report_id}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Generated On: {timestamp}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    # ==================================================
    # PATIENT INFORMATION
    # ==================================================

    content.append(
        Paragraph(
            "Patient Information",
            styles["Heading1"]
        )
    )

    patient_table_data = [

        ["Field", "Value"],

        ["Age", str(patient_data["age"])],

        ["Gender", str(patient_data["gender"])],

        ["Blood Pressure (mmHg)",
         str(patient_data["bp"])]

    ]

    patient_table = Table(
        patient_table_data,
        colWidths=[220, 220]
    )

    patient_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.lightblue),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold")
        ])
    )

    content.append(patient_table)

    content.append(Spacer(1, 20))

    # ==================================================
    # LABORATORY PARAMETERS
    # ==================================================

    content.append(
        Paragraph(
            "Laboratory Parameters",
            styles["Heading1"]
        )
    )

    lab_table_data = [

        ["Parameter", "Value"],

        ["Specific Gravity",
         str(patient_data["sg"])],

        ["Albumin",
         str(patient_data["al"])],

        ["Sugar",
         str(patient_data["su"])],

        ["Red Blood Cells",
         "Normal" if patient_data["rbc"] == 0 else "Abnormal"],

        ["Pus Cells",
         "Normal" if patient_data["pc"] == 0 else "Abnormal"],

        ["Pus Cell Clumps",
         "Absent" if patient_data["pcc"] == 0 else "Present"],

        ["Bacteria",
         "Absent" if patient_data["ba"] == 0 else "Present"],

        ["Blood Glucose Random",
         str(patient_data["bgr"])],

        ["Blood Urea",
         str(patient_data["bu"])],

        ["Serum Creatinine",
         str(patient_data["sc"])],

        ["Sodium",
         str(patient_data["sod"])],

        ["Potassium",
         str(patient_data["pot"])],

        ["Hemoglobin",
         str(patient_data["hemo"])],

        ["Packed Cell Volume",
         str(patient_data["pcv"])],

        ["White Blood Cell Count",
         str(patient_data["wc"])],

        ["Red Blood Cell Count",
         str(patient_data["rc"])],

        ["Hypertension",
         "Yes" if patient_data["htn"] == 1 else "No"],

        ["Diabetes Mellitus",
         "Yes" if patient_data["dm"] == 1 else "No"],

        ["Coronary Artery Disease",
         "Yes" if patient_data["cad"] == 1 else "No"],

        ["Appetite",
         "Good" if patient_data["appet"] == 1 else "Poor"],

        ["Pedal Edema",
         "Yes" if patient_data["pe"] == 1 else "No"],

        ["Anemia",
         "Yes" if patient_data["ane"] == 1 else "No"]

    ]

    lab_table = Table(
        lab_table_data,
        colWidths=[250, 180]
    )

    lab_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS",
             (0,1),
             (-1,-1),
             [colors.whitesmoke, colors.lightcyan])
        ])
    )

    content.append(lab_table)

    content.append(Spacer(1, 20))

    # ==================================================
    # AI ASSESSMENT SUMMARY
    # ==================================================

    content.append(
        Paragraph(
            "AI Assessment Summary",
            styles["Heading1"]
        )
    )

    summary_table_data = [

        ["Metric", "Value"],

        ["CKD Probability (%)",
         str(report["ckd_probability"])],

        ["AI Risk Level",
         report["ai_risk_level"]],

        ["Health Score",
         str(report["health_score"])],

        ["Reliability Score",
         str(report["reliability_score"])],

        ["Reliability Level",
         report["reliability_level"]]

    ]

    summary_table = Table(
        summary_table_data,
        colWidths=[220, 220]
    )

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.lightgreen),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold")
        ])
    )

    content.append(summary_table)

    content.append(Spacer(1, 20))

    # ==================================================
    # KIDNEY FUNCTION SUMMARY
    # ==================================================

    content.append(
        Paragraph(
            "Kidney Function Summary",
            styles["Heading1"]
        )
    )

    kidney_table_data = [

        ["Metric", "Value"],

        ["eGFR",
         str(report["egfr"])],

        ["CKD Stage",
         report["ckd_stage"]],

        ["Health Category",
         report["health_category"]]

    ]

    kidney_table = Table(
        kidney_table_data,
        colWidths=[220, 220]
    )

    kidney_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.lavender),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold")
        ])
    )

    content.append(kidney_table)

    content.append(Spacer(1, 20))

    # ==================================================
    # OVERALL ASSESSMENT
    # ==================================================

    content.append(
        Paragraph(
            "Overall Assessment",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            report["overall_assessment"],
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    # ==================================================
    # KEY FINDINGS
    # ==================================================

    content.append(
        Paragraph(
            "Key Findings",
            styles["Heading1"]
        )
    )

    if report["key_findings"]:

        for item in report["key_findings"]:

            content.append(
                Paragraph(
                    f"• {item}",
                    styles["Normal"]
                )
            )

    else:

        content.append(
            Paragraph(
                "No major abnormalities detected.",
                styles["Normal"]
            )
        )

    content.append(PageBreak())

    # ==================================================
    # CLINICAL FINDINGS
    # ==================================================

    content.append(
        Paragraph(
            "Clinical Findings",
            styles["Title"]
        )
    )

    sections = [

        ("Urine Findings",
         report["urine_findings"],
         "No urine abnormalities detected."),

        ("Blood Findings",
         report["blood_findings"],
         "No blood abnormalities detected."),

        ("Kidney Findings",
         report["kidney_findings"],
         "No kidney abnormalities detected."),

        ("Risk Factors",
         report["risk_factors"],
         "No significant risk factors detected.")

    ]

    for title, findings, empty_msg in sections:

        content.append(
            Paragraph(
                title,
                styles["Heading2"]
            )
        )

        if findings:

            for item in findings:

                content.append(
                    Paragraph(
                        f"• {item}",
                        styles["Normal"]
                    )
                )

        else:

            content.append(
                Paragraph(
                    empty_msg,
                    styles["Normal"]
                )
            )

        content.append(Spacer(1, 10))

    # ==================================================
    # RECOMMENDATIONS
    # ==================================================

    content.append(
        Paragraph(
            "Recommendations",
            styles["Heading1"]
        )
    )

    for item in report["recommendations"]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 20))

    # ==================================================
    # DISCLAIMER
    # ==================================================

    content.append(
        Paragraph(
            "Disclaimer",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            """
            This report is generated using an Artificial Neural Network
            and clinical rule-based analysis system. It is intended
            for educational purposes only and does not replace
            professional medical advice.
            """,
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 30))

    # ==================================================
    # PROJECT FOOTER
    # ==================================================

    content.append(
        Paragraph(
            "────────────────────────────────────",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            "AI Kidney Health Assessment System",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            "Developed by: Syed Shaheer Hussain",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            "B.Tech Electronics & Communication Engineering",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            "VIT-AP University",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            "Artificial Intelligence + Healthcare Analytics Project",
            styles["Normal"]
        )
    )

    doc.build(content)

    buffer.seek(0)

    return buffer